# Generated by Django 3.1.4 on 2021-01-25 21:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('company_url', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/')),
                ('contact', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('INDEP', 'Independent'), ('ASSOC', 'Associated')], max_length=5)),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('updated_on', models.DateField(default=datetime.date.today)),
                ('attachment', models.FileField(blank=True, upload_to='cv_uploads/')),
                ('comments', models.TextField(blank=True)),
                ('cover_letter', models.TextField(blank=True)),
                ('application_response', models.BooleanField(default=False)),
                ('response_content', models.TextField(blank=True)),
                ('applied_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jboffer.company')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=255)),
                ('offer_pic', models.ImageField(blank=True, upload_to='scrshots/')),
                ('offer_url', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=80)),
                ('position', models.CharField(max_length=100)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jboffer.myapplication')),
            ],
        ),
    ]
