# Generated by Django 3.1.4 on 2021-01-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplication',
            name='updated_on',
            field=models.DateField(auto_now=True),
        ),
    ]
