# Generated by Django 3.1.4 on 2021-01-28 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0004_auto_20210127_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='myapplication',
            name='position',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='myapplication',
            name='applied_to',
            field=models.ForeignKey(default='Select a company name', null=True, on_delete=django.db.models.deletion.CASCADE, to='jboffer.company'),
        ),
        migrations.AlterField(
            model_name='myapplication',
            name='comments',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
