# Generated by Django 3.1.4 on 2021-01-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0005_auto_20210128_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplication',
            name='applied_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
