# Generated by Django 3.1.4 on 2021-01-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0006_auto_20210128_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True, verbose_name='Tags')),
                ('applications', models.ManyToManyField(related_name='tags', to='jboffer.MyApplication')),
            ],
        ),
    ]
