# Generated by Django 3.1.4 on 2021-01-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0007_applicationtag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtag',
            name='name',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Tags'),
        ),
    ]
