# Generated by Django 3.1.4 on 2021-01-29 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0008_auto_20210128_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplication',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
