# Generated by Django 3.1.4 on 2021-02-02 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0010_auto_20210129_2332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joboffer',
            old_name='offer_pic',
            new_name='snapshot',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='contact_email',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='offer_url',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='position',
        ),
        migrations.RemoveField(
            model_name='joboffer',
            name='short_description',
        ),
        migrations.AddField(
            model_name='joboffer',
            name='description',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='joboffer',
            name='url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jboffer.myapplication'),
        ),
    ]
