# Generated by Django 3.1.4 on 2021-02-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jboffer', '0011_auto_20210202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myapplication',
            name='position',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
